### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by jackpaster** [ambas/ColorPicker#2]
Could you create a fix so this project can run on swift 3.0

**Comment by jackpaster** [comment]
could you update your pod file

**Comment by jackpaster** [comment]
Are you going to update. Please

**Comment by jackpaster** [comment]
@ambas can you please help update the pods of this great project

**Comment by ambas** [comment]
@jackpaster Hi. Thanks for using it, I will try to update in this weekend :)

**Comment by jackpaster** [comment]
thank you so much

**Comment by jackpaster** [comment]
@ambas can you update to swift 3.0 and not 2.3 please

**Comment by jackpaster** [comment]
@ambas Hi, I thought you said you would try to have it done by the weekend. Have you finished or were you unable to complete the update. Thanks

**Comment by Ahmedshubber** [comment]
+1

**Comment by jackpaster** [comment]
@ambas what happened.

**Comment by jackpaster** [comment]
Can you help me

**Comment by jackpaster** [comment]
@ambas can you please fix your project to swift 3.0
